site_1/food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    path('', views.indexclassview.as_view(), name = "item"),
    path('<int:pk>/',views.detailclassview.as_view(), name = "detail"),
    path('index/', views.index, name = "food"),
    # add items
    path('add/', views.create_itemclassview.as_view(), name='create_item'),
    #edit items
    path('update/<int:id>', views.update_item, name='update_items'),
    #delete items
    path('delete/<int:id>', views.delete_item, name = "delete_item"),
    
]

site_1/site_1/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('item/', include("food.urls")),
    path('register/', user_views.register, name = 'register'), 
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('profile/', user_views.profilepage, name = 'profile')
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_1/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete = models.CASCADE, default = 1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price =  models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

site_1/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profilepictures')
    location = models.CharField(default = 'No Location', max_length = 100)  

    def __str__(self):
        return self.user.username

site_1/food/forms.py
from django import forms
from .models import Item    

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    

site_1/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

site_1/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.

def item(request):
    item_list = Item.objects.all()
    # template = loader.get_template('food/index.html') # one way to do render html
    context = {
    'item_list' : item_list
    }
    #  return HttpResponse(template.render(context,request))
    return render(request, 'food/index.html', context)

class indexclassview(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'

def index(request):
    return HttpResponse("Hello food")

# def detail(request, item_id):
#     item = Item.objects.get(pk = item_id)
#     context = {
#         'item' : item
#     } 
#     return render(request, 'food/detail.html', context)

class detailclassview(DetailView):
    model = Item
    template_name = 'food/detail.html'

# def create_item(request):
#     form = ItemForm(request.POST or None)

#     if form.is_valid():
#         form.save()
#         return redirect('food:item')
    
#     return render(request, "food/item-form.html", {'form': form})

class create_itemclassview(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request,id):
    item = Item.objects.get(id = id)
    form = ItemForm(request.POST or None, instance = item)

    if form.is_valid():
        form.save()
        return redirect('food:item')
    
    return render(request, 'food/item-form.html', {'form': form, 'item': item})

def delete_item(request, id):
    item = Item.objects.get(id = id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:item')
    
    return render(request, 'food/item-delete.html', {'item': item})
    
    

site_1/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, your account has been created!')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

site_1/food/templates/food/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">

    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script> -->
    <title>Document</title>
</head>

<body>
        <nav class="navbar navbar-dark bg-dark">
            <a href="#" class="navbar-brand">Site_1</a>

            <div class="navbar">
                <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
                <a class="nav-item nav-link" href="#">Delete Item</a>
                <a class="nav-item nav-link" href="#">View Item</a>
                {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}">Logout</a>
                    <a href="{% url 'profile' %}">Profile</a>
                {% else %}
                    <a href="{% url 'login' %}">Login</a>
                {% endif %}
            </div>
        </nav>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}}">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    {% block body %}
    {% endblock %}
</body>

</html>

site_1/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src="{{item.item_image}}" class="card" />
        </div>
        <div class="col-md-6">
            <h1>{{object.item_name}}</h1>
            <h2>{{object.item_desc}}</h2>
            <h3>${{object.item_price}}</h3>
            <br></br>
            <a href="{% url 'food:delete_item' item.id %}" class = 'btn btn-success'>Delete Item</a>
        </div>
    </div>
</div>
{% endblock %}

site_1/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    {% block body %}

    {%for item in item_list%}

    <div class="row">
        <div class="col-md-2 offset-md-1">
            <img class="card" height="200px" width="200px" src="{{item.item_image}}" />
        </div>
        <div class="col-md-5">
            <h3>{{item.item_name}}</h3>
            <h4>{{item.item_desc}}</h4>
            <h5>${{item.item_price}}</h5>
            <h6>{{ item.user_name }}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            <a href="{% url 'food:update_items' item.id %}" class = "btn btn-success">Edit</a>
        </div>

    </div>

    {%endfor%}

    {% endblock %}

    <!-- old code :/ -->
    <!-- <ul>
        <li>
            <a href="{% url 'food:detail' item.id %}">{{item.id}} -- {{item.item_name}}</a>
        </li>
    </ul> -->


</body>

</html>

site_1/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}}?</h2>
    <button type = "submit" >Confirm</button>
</form>

site_1/food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 mx-auto">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title mx-auto">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class = 'form-group'>
                            {{field.name}}
                            {{field}}
                        </div>
                        {% endfor %}
                        <button type="submit"  class = "btn-info mx-auto d-block">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}




<form method="POST">
    {% csrf_token %}
    {% for field in form %}
        <div class = 'form-group'>
            {{field.name}}
            <br>
            {{field}}
        </div>
    {% endfor %}
    <button type="submit" class = "btn-info mx-auto d-block">Sign Up</button>
</form>

site_1/users/templates/users/login.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">

    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script> -->
    <!-- <title>Document</title>     -->
</head>

<body>
        <nav class="navbar navbar-dark bg-dark">
            <a href="#" class="navbar-brand">Site_1</a>
        </nav>
</body>
<!-- {% block body %} -->

<div class="container">
    <div class="row">
        <div class="col-md-4 mx-auto">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class = "form-group">
                                {{field.name}}
                                {{field}}
                            </div>
                        {% endfor %}
                        <button type="submit" class = " btn-info mx-auto d-block">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


</html>
<!-- {% endblock %} -->

site_1/users/templates/users/logout.html
<h1>You have been logged out</h1>
<head>
<meta http-equiv="refresh" content="3; URL=http://127.0.0.1:8000/login/" />
</head>

site_1/users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img width = "100px" height="100px" src = "{{user.profile.image.url}}">
<h3>{{ user.profile.location }}</h3>

site_1/users/templates/users/register.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">

    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script> -->
    <!-- <title>Document</title>     -->
</head>

<body>
        <nav class="navbar navbar-dark bg-dark">
            <a href="#" class="navbar-brand">Site_1</a>
        </nav>
</body>

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 mx-auto">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class = 'form-group'>
                                {{field.name}}
                                <br>
                                {{field}}
                            </div>
                        {% endfor %}
                        <button type="submit" class = "btn-info mx-auto d-block">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

</html>